#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

[[ ! -d '/sys/class/power_supply/AC' ]] && exit

plugged_in="$(cat /sys/class/power_supply/AC/online)"

cap=100
if [[ -n "$BLOCK_INSTANCE" ]]; then
  cap=$((($(cat "/sys/class/power_supply/$BLOCK_INSTANCE/capacity") + $cap) / 2))
else
  for battery in /sys/class/power_supply/BAT*; do
    cap=$((($(cat "$battery/capacity") + $cap) / 2))
  done
fi

if [[ -e /usr/bin/acpi ]]; then
  dtime=" ($(acpi | grep -o '[0-9]*:[0-9]*:[0-9]*' | cut -d: -f1,2))"
elif [[ -e '/sys/class/power_supply/BAT0/time_to_empty' ]] ||
     [[ -e '/sys/class/power_supply/BAT0/time_to_full' ]]; then
  dtime=" ($(cat /sys/class/power_supply/BAT0/time_to_empty))"
  ((plugged_in)) && dtime="$(cat /sys/class/power_supply/BAT0/time_to_full)"
fi

((plugged_in)) && echo -n '+' || echo -n '-'
echo "$cap%$dtime"
