#!/usr/sbin/bash

info="$(acpi --battery)"
# echo $info
batt_status="$(echo $info | awk '{print $3}')"
# echo $batt_status
if [ "$batt_status" == "Discharging," ]; then
    batt_level="$(echo $info | awk '{print $4}' | rev | cut -c3- | rev)"
    batt_remain="$(echo $info | awk '{print $5}' | rev | cut -d ":" -f2- | rev)"
    if [ $batt_level -le 20 ]; then
	color="#FF0000"
	notify-send --urgency=critical --expire-time=5000 "Battery level lower that 20%, Recharg it."
    elif [ $batt_level -le 40 ]; then
	color="#FFAE00"
	# notify-send --urgency=normal --expire-time=5000 "Battery level lower that 40%, Recharg it."
    elif [ $batt_level -le 60 ]; then
	color="#FFF600"
    elif [ $batt_level -le 85 ]; then
	color="A8FF00"
    fi
    full_text="DIS $batt_level%($batt_remain)"
    full_text="DIS $batt_level%($batt_remain)"
    color="$color"
elif [ "$batt_status" == "Charging," ]; then
    batt_level="$(echo $info | awk '{print $4}' | rev | cut -c2- | rev)"
    batt_remain="$(echo $info | awk '{print $5}')"
    if [ "$batt_remain" == "until" ]; then
	batt_remain="--"
    else
	batt_remain="$(echo $batt_remain | cut -d ":" -f2- )"
    fi
    full_text="CHR $batt_level($batt_remain)"
    full_text="CHR $batt_level($batt_remain)"
    color="#90EE90"
elif [ "$batt_status" == "Full," ]; then
    batt_level="$(echo $info | awk '{print $4}')"
    full_text="Full $batt_level"
    full_text="Full $batt_level"
    color="#FFFF00"
elif [ "$batt_status" == "Unknown," ]; then
    # if [ "$(echo $info | awk '{print $4}')" == "100%" ]; then
    batt_level="$(echo $info | awk '{print $4}')"
    full_text="Full $batt_level"
    full_text="Full $batt_level"
    color="#FFFF00"
    # fi
else
        full_text="No Batt"
        full_text="No Batt"
        color="FF0000"
fi

echo $full_text
echo $full_text
echo $color
