#!/bin/sh

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

user1=$(awk '/^cpu / { print $2 }' /proc/stat)
nice1=$(awk '/^cpu / { print $3 }' /proc/stat)
system1=$(awk '/^cpu / { print $4 }' /proc/stat)
idle1=$(awk '/^cpu / { print $5 }' /proc/stat)

sleep 1

user2=$(awk '/^cpu / { print $2 }' /proc/stat)
nice2=$(awk '/^cpu / { print $3 }' /proc/stat)
system2=$(awk '/^cpu / { print $4 }' /proc/stat)
idle2=$(awk '/^cpu / { print $5 }' /proc/stat)

busy1=$(( $user1 + $nice1 + $system1 ))
busy2=$(( $user2 + $nice2 + $system2 ))
total1=$(( $user1 + $nice1 + $system1 + $idle1 ))
total2=$(( $user2 + $nice2 + $system2 + $idle2 ))

busy=$(( $busy2 - $busy1 ))
total=$(( $total2 - $total1 ))

echo "$busy $total" | awk '{ printf("%.2f%%\n", $1 / $2 * 100) }'
