#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

# Use the provided interface, otherwise the device used for the default route.
if [[ -n "$BLOCK_INSTANCE" ]]; then
  IF="$BLOCK_INSTANCE"
else
  IF="$(ip route | awk '/^default/ { print $5 }')"
fi

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d "/sys/class/net/${IF}" ]] && exit


if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
  echo 'down'
  exit
fi

case "$1" in
  -4)
    AF='inet' ;;
  -6)
    AF='inet6' ;;
  *)
    AF='inet6?' ;;
esac

# If no interface is found, use the first global scope address
IPADDR="$(ip addr show $IF |
            awk "/$AF.*/ { split(\$2, out, /\//); print(out[1]) }" |
            head -n 1)"

#------------------------------------------------------------------------

case "$BLOCK_BUTTON" in
  3) echo -n "$IPADDR" | xclip -q -se c ;;
esac

echo "$IPADDR"
