#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

INTERFACE="${BLOCK_INSTANCE:-eth0}"

state () {
  cat /sys/class/net/$INTERFACE/operstate
}
 
speed () {
  cat /sys/class/net/$INTERFACE/speed 2> /dev/null
}
 
ipv4 () {
  ip addr show $INTERFACE | perl -n -e '/inet ([^\/]+).*? scope global/ && print $1'
}
 
ipv6 () {
  ip -6 addr show $INTERFACE | perl -n -e '/inet6 ([^\/]+).*? scope global/ && print $1'
}

if [ "$(state)" != 'up' ]; then
  echo down # full text
  echo down # short text
  echo \#FF0000 # color
  exit 0
fi

IPADDR="No Addr"
[[ $1 != '-6' ]] && [[ -n $(ipv4) ]] && IPADDR=$(ipv4)
[[ $1 != '-4' ]] && [[ -n $(ipv6) ]] && IPADDR=$(ipv6)

case $BLOCK_BUTTON in
  3) echo -n "$IPADDR" | xclip -q -se c; exit 0;;
esac

# full text
echo -n "$IPADDR"
SPEED=$(speed)
[ -n "$SPEED" ] && echo " ($SPEED Mbits/s)" || echo
 
# short text
echo "$IPADDR"
