#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

INTERFACE="${BLOCK_INSTANCE:-eth0}"

ipv4 () {
  ip addr show $INTERFACE | perl -n -e '/inet ([^ ]+).*? scope global/ && print $1'
}
 
ipv6 () {
  ip -6 addr show $INTERFACE | perl -n -e '/inet6 ([^ ]+).*? scope global/ && print $1'
}

if [ "$(cat /sys/class/net/$INTERFACE/operstate)" != 'up' ]; then
  echo down # full text
  echo down # short text
  echo \#FF0000 # color
  exit 0
fi

ipaddr="No Addr"
[[ $1 != '-6' ]] && [[ -n $(ipv4) ]] && ipaddr=$(ipv4)
[[ $1 != '-4' ]] && [[ -n $(ipv6) ]] && ipaddr=$(ipv6)

case $BLOCK_BUTTON in
  3) echo -n "$ipaddr" | xclip -q -se c;;
esac

level=$(sed -n "s/${INTERFACE}: *[0-9]* *\\([0-9]*\\).*/\\1/p" </proc/net/wireless)
signal="$(echo "$level * 1.42857142857" | bc | awk '{print int($1 + 0.5)}')%"

speed="$(cat /sys/class/net/$INTERFACE/speed)"
[[ speed -eq 10000 ]] && speed="10Gb"
[[ speed -eq 1000 ]] && speed="1Gb"
[[ speed -eq 100 ]] && speed="100Mb"
[[ speed -eq 10 ]] && speed="10Mb"

# full text
echo "$ipaddr (${signal:-$speed})"

# short text
echo "$ipaddr"
