#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

# The first parameter overrides the mixer selection
# For PulseAudio users, use "pulse"
# For ALSA users, you may use "default" for your primary card
# or you may use hw:# where # is the number of the card desired
MIXER="default"
[ -n "$(lsmod | grep pulse)" ] && MIXER="pulse"
MIXER="${2:-$MIXER}"

# The instance option sets the control to report and configure
# This defaults to the first control of your selected mixer
# For a list of the available, use `amixer -D $Your_Mixer scontrols`
SCONTROL="${BLOCK_INSTANCE:-$(amixer -D $MIXER scontrols |
                  sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" |
                  head -n1
                )}"

#------------------------------------------------------------------------

capability() { # Return "Capture" if the device is a capture device
  amixer -D "$MIXER" get "$SCONTROL" |
    awk '/^Capabilities:.*cvolume/ { print "Capture" }'
}

#------------------------------------------------------------------------

case "$BLOCK_BUTTON" in
  3) amixer -q -D "$MIXER" sset "$SCONTROL" "$(capability)" toggle ;; # right click, mute/unmute
  4) amixer -q -D "$MIXER" sset "$SCONTROL" "$(capability)" unmute ;; # scroll up, increase
  5) amixer -q -D "$MIXER" sset "$SCONTROL" "$(capability)" unmute ;; # scroll down, decrease
esac

amixer -D "$MIXER" get "$SCONTROL" "$(capability)" | grep -oP '\d{1,3}%' | head -n 1
