#!/bin/sh

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

# Use the provided interface, otherwise the device used for the default route.
if [[ -n "$BLOCK_INSTANCE" ]]; then
  IF="$BLOCK_INSTANCE"
else
  IF="$(grep -o '.*:' /proc/net/wireless | tr -d ':')"
fi

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${IF}/wireless ]] ||
  [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

grep $IF /proc/net/wireless | awk '{ printf("%d%%\n", $3 * 100 / 70) }'
