'\" t
.\"     Title: i3blocks
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2019-08-12
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "I3BLOCKS" "1" "2019-08-12" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
i3blocks \- A feed generator for text based status bars
.SH "SYNOPSIS"
.sp
\fBi3blocks\fP [\fIOPTION\fP]...
.SH "DESCRIPTION"
.sp
The i3blocks(1) command generates a status line for i3bar(1).
It schedules command lines described in a simple configuration file at specified time intervals, upon signal reception or on clicks.
.SH "OPTIONS"
.sp
\fB\-h\fP
.RS 4
Show the help message and exit.
.RE
.sp
\fB\-c\fP \fICONFIGFILE\fP
.RS 4
Specifies an alternate configuration file path.
.RE
.sp
\fB\-v\fP
.RS 4
Increase log level.
This option is a cumulative.
By default only fatal errors are shown in the status bar.
Passing this option once will show error messages as well.
Using \fB\-vv\fP and more will show more debug output on standard error.
.RE
.SH "CONFIGURATION"
.sp
i3blocks must be defined as the status line command of the \fBbar\fP block described in your i3(1) configuration file:
.sp
.if n .RS 4
.nf
bar {
  status_command i3blocks
}
.fi
.if n .RE
.sp
By default, i3blocks looks for a configuration file in the following order (note that /etc may be prefixed with /usr/local depending on the compilation flags):
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
\fI$XDG_CONFIG_HOME/i3blocks/config\fP (or \fI~/.config/i3blocks/config\fP)
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
\fI~/.i3blocks.conf\fP
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 3." 4.2
.\}
\fI$XDG_CONFIG_DIRS/i3blocks/config\fP (or \fI/etc/xdg/i3blocks/config\fP)
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 4." 4.2
.\}
\fI/etc/i3blocks.conf\fP
.RE
.sp
For the content of the configuration file, please refer to the i3blocks website: \c
.URL "https://vivien.github.io/i3blocks" "" ""
.SH "SEE ALSO"
.sp
i3(1), i3bar(1), i3status(1)
.SH "AUTHORS"
.sp
i3blocks is written by Vivien Didelot and other contributors.
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://vivien.github.io/i3blocks" "" ""
.sp
\fBGit source repository and issue tracker:\fP \c
.URL "https://github.com/vivien/i3blocks" "" ""
.sp
\fBOfficial collection of scripts for i3blocks:\fP \c
.URL "https://github.com/vivien/i3blocks\-contrib" "" ""
.sp
\fBi3bar protocol:\fP \c
.URL "http://i3wm.org/docs/i3bar\-protocol.html" "" ""
.SH "COPYING"
.sp
Copyright \(co Vivien Didelot.
Free use of this software is granted under the terms of the \fIGPLv3+\fP License.