require 'asciidoctor'

task :default do
  Asciidoctor.convert_file 'README.adoc', safe: :unsafe, to_file: 'index.html', attributes: { 'reproducible' => true, 'toc' => 'left' }
  Asciidoctor.convert_file 'blocklets.adoc', safe: :unsafe, attributes: { 'reproducible' => true }
  Asciidoctor.convert_file 'i3blocks.1.adoc', safe: :unsafe, attributes: { 'reproducible' => true, 'toc' => 'left' }
  Asciidoctor.convert_file 'i3blocks.1.adoc', safe: :unsafe, backend: :manpage
end
